// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itdnhrorgpaljxuazqgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZG5ocm9yZ3BhbGp4dWF6cWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTcxMzUsImV4cCI6MjA3MzY5MzEzNX0.kJ2Fh5r49D8nYQK1c087yRSN8vK6IUpudLKiH36QfXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});